version: '3'

services: 
    node: 
        build: .
        container_name: node-backend
        ports: 
            - "7777:7777"
        depends_on: 
            - mongo
            - redis
    mongo:
        image: mongo:latest
        container_name: mongo-db
        volumes: 
            - "data-db:/data/db"
    redis:
        image: redis:latest
        container_name: redis
volumes: 
    data-db: