version: '3'

services: 
    node: 
        build: .
        container_name: node-backend
        environment: 
            - PORT: ${PORT}
            - MONGODB_URL: ${MONGODB_URL}
            - REDIS_PORT: ${REDIS_PORT}
            - REDIS_HOST: ${REDIS_HOST}
        ports: 
            - "7777:7777"
        depends_on: 
            - mongo
            - redis
    mongo:
        image: mongo:latest
        container_name: mongo-db
        volumes: 
            - "data-db:/data/db"
    redis:
        image: redis:latest
        container_name: redis
volumes: 
    data-db: